from __future__ import annotations
from dataclasses import dataclass, field

from pathlib import Path
from typing import Final, Iterable, List,  Optional, Sequence, Union, TYPE_CHECKING
import pandas as pd

if TYPE_CHECKING:
    from matplotlib.figure import Figure
    from matplotlib.axes import Axes

Pathlike = Union[str, Path]
EXG_PREFIX: Final[str] = "EXG Channel "


@dataclass
class DataReader():
    '''
    DataLoader and basic handler for OpenBCI log files
        - supports both csv and txt files 
    '''
    file_path: Pathlike
    
    auto_load:bool = field(default=True, repr=False)

    comment_char: str = field(default='%', repr=False)  # comment lines in txt files
    # the csv file uses the horizontal tab (ASCII code 9 or \t) to seperate the values
    seperation_value: str = field(default=chr(9), repr=False)
    # since the csv file generated by the OpenBCi board and logged by its software
    # does not have headers we can use this list extracted from the txt file to use
    # as the column names for convenience
    # csv file does not have Timestamp (formated) column so it will be droped
    coloums: list = field(default_factory=lambda:
                          ['Sample Index', 'EXG Channel 0', 'EXG Channel 1', 'EXG Channel 2',
                           'EXG Channel 3', 'EXG Channel 4', 'EXG Channel 5', 'EXG Channel 6',
                           'EXG Channel 7', 'Accel Channel 0', 'Accel Channel 1',
                           'Accel Channel 2', 'Not Used', 'Digital Channel 0 (D11)',
                           'Digital Channel 1 (D12)', 'Digital Channel 2 (D13)',
                           'Digital Channel 3 (D17)', 'Not Used.1', 'Digital Channel 4 (D18)',
                           'Analog Channel 0', 'Analog Channel 1', 'Analog Channel 2',
                           'Timestamp', 'Marker Channel', 'Timestamp (Formatted)'],
                           repr=False
                        )

   # private class variable for dataframe
    _df: Optional[pd.DataFrame] = field(default=None, init=False, repr=False)

    def __post_init__(self) -> None:
        self.path = Path(self.file_path)
        if not self.path.exists():
            raise FileNotFoundError(f"File Not Found: {self.path}")
        if self.auto_load:
            self.load()

    def load(self) -> pd.DataFrame:
        '''
        load the OpenBCI file into pandas dataframe
            - can parse both txt and csv files 
            - will assign proper header names to csv file

        Returns
        ----------
        pd.Datafarme

        '''
        if self.path.suffix == '.csv':
            df = pd.read_csv(self.path, sep=self.seperation_value, header=None)
            df.columns = self.coloums[:-1] #dropping formated timestamps

        elif self.path.suffix == '.txt':
            df = pd.read_csv(self.path, comment=self.comment_char)
            # light clean up of the column names 
            df.columns = df.columns.str.strip()

        else:
            raise TypeError(f"File Type Not supported")
        
        self._df = df
        return df
    
    @property
    def df(self) -> pd.DataFrame:
        """
        Return the loaded DataFrame; raise if not loaded
        """
        if self._df is None:
            raise RuntimeError(
                "Data Not Loaded. Call .load() first"
            )
        return self._df


if __name__ == "__main__":
    dr = DataReader("./data/BrainFlow-RAW_2025-11-01_17-07-18_0.csv")
    print(dr.df.head())
